version: '3.8'

services:
  odonto-frontend:
    build: .
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    
  # Opcional: Adicionar backend
  # odonto-backend:
  #   image: node:18-alpine
  #   ports:
  #     - "3001:3001"
  #   environment:
  #     - NODE_ENV=production
  #     - DATABASE_URL=postgresql://user:password@db:5432/odonto
  #   restart: unless-stopped
  
  # Opcional: Banco de dados
  # db:
  #   image: postgres:15-alpine
  #   environment:
  #     - POSTGRES_DB=odonto
  #     - POSTGRES_USER=user
  #     - POSTGRES_PASSWORD=password
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   restart: unless-stopped

# volumes:
#   postgres_data: